#!/usr/bin/env bash
# ------------------------------------------------------------
# setup.sh – one‑click bootstrap for the NixOS‑WSL dev‑profile repo
# ------------------------------------------------------------
# What it does:
#   1️⃣ Enable flakes in ~/.config/nix/nix.conf
#   2️⃣ Install nix-direnv and add the direnv hook
#   3️⃣ Install home‑manager
#   4️⃣ Migrate legacy ~/.config/nixpkgs/home.nix → ~/.config/home-manager/home.nix
#   5️⃣ Create a minimal home.nix (if missing) that imports the shared main.nix
#   6️⃣ Generate hardware‑configuration.nix (if missing)
#   7️⃣ Rebuild the WSL NixOS system (nixosConfigurations.wsl)
#   8️⃣ Remind you to restart WSL
# ------------------------------------------------------------

set -euo pipefail
IFS=$'\n\t'

# ---------- Helper functions ----------
info()  { printf "\033[1;34m[INFO]\033[0m %s\n" "$*"; }
warn()  { printf "\033[1;33m[WARN]\033[0m %s\n" "$*"; }
error() { printf "\033[1;31m[ERROR]\033[0m %s\n" "$*" >&2; exit 1; }

# ---------- 1️⃣ Ensure flakes are enabled ----------
ensure_nix_conf() {
  local conf_dir="${HOME}/.config/nix"
  local conf_file="${conf_dir}/nix.conf"

  mkdir -p "${conf_dir}"
  if [[ -f "${conf_file}" && $(grep -c "experimental-features" "${conf_file}") -gt 0 ]]; then
    info "Nix config already contains experimental‑features."
  else
    info "Creating/updating ${conf_file} to enable flakes."
    {
      echo "# Added by nixos‑config/setup.sh"
      echo "experimental-features = nix-command flakes"
    } >> "${conf_file}"
  fi
}

# ---------- 2️⃣ Install nix‑direnv ----------
install_nix_direnv() {
  if nix profile list | grep -q nix-direnv; then
    info "nix-direnv already installed in the user profile."
  else
    info "Installing nix-direnv ..."
    nix profile install nixpkgs#nix-direnv
  fi

  # Detect the user’s shell rc file (bash or zsh)
  local rc_file=""
  if [[ -n "${BASH_VERSION-}" ]]; then
    rc_file="${HOME}/.bashrc"
  elif [[ -n "${ZSH_VERSION-}" ]]; then
    rc_file="${HOME}/.zshrc"
  else
    warn "Cannot detect bash or zsh. Please add 'eval \"$(nix-direnv)\"' to your shell startup manually."
    return
  fi

  if grep -Fxq 'eval "$(nix-direnv)"' "${rc_file}" 2>/dev/null; then
    info "direnv hook already present in ${rc_file}"
  else
    info "Appending direnv hook to ${rc_file}"
    {
      echo ""
      echo "# Added by nixos‑config/setup.sh – enable nix‑direnv"
      echo 'eval "$(nix-direnv)"'
    } >> "${rc_file}"
  fi
}

# ---------- 3️⃣ Install home‑manager ----------
install_home_manager() {
  if nix profile list | grep -q home-manager; then
    info "home-manager already installed in the user profile."
  else
    info "Installing home-manager ..."
    nix profile install nixpkgs#home-manager
  fi
}

# ---------- 4️⃣ Migrate legacy home.nix ----------
migrate_legacy_home_nix() {
  local old_path="${HOME}/.config/nixpkgs/home.nix"
  local new_dir="${HOME}/.config/home-manager"
  local new_path="${new_dir}/home.nix"

  if [[ -f "${old_path}" ]]; then
    info "Legacy home.nix found at ${old_path} – migrating to ${new_path}"
    mkdir -p "${new_dir}"
    mv "${old_path}" "${new_path}"
    # Keep a symlink for backward compatibility (optional)
    ln -sf "${new_path}" "${old_path}"
  else
    info "No legacy home.nix to migrate."
  fi
}

# ---------- 5️⃣ Create minimal home.nix if missing ----------
create_home_nix_if_missing() {
  local home_dir="${HOME}/.config/home-manager"
  local home_file="${home_dir}/home.nix"

  if [[ -f "${home_file}" ]]; then
    info "home.nix already exists at ${home_file}"
    return
  fi

  info "Creating a minimal home.nix at ${home_file}"

  # Detect the NixOS version we are running (e.g. 24.05, 25.05, …)
  # `nixos-version` prints something like "24.05 (Hydra)" – we keep the first field.
  local nixos_version
  nixos_version=$(nixos-version | awk '{print $1}')

  cat > "${home_file}" <<EOF
# ~/.config/home-manager/home.nix
# ------------------------------------------------------------
# Minimal Home Manager configuration – generated by setup.sh
# ------------------------------------------------------------
{ pkgs, ... }:

let
  # Import the shared configuration from the repo.
  # Adjust the path if you keep the repo somewhere else.
  shared = import "${HOME}/nixos-config/main.nix" { inherit pkgs; };
in {
  # Required: tell Home Manager which version of its options to use.
  home.stateVersion = "${nixos_version}";

  # Packages that should be installed globally for your user.
  home.packages = shared.commonPackages;

  # Environment variables (EDITOR, LANG, …)
  home.sessionVariables = shared.env;

  # Example: enable Zsh (feel free to customise further)
  programs.zsh.enable = true;
  programs.zsh.promptInit = ''
    PROMPT='%F{green}%n@%m %F{blue}%~ %F{yellow}\$ %f'
  '';
}
EOF
}

# ---------- 6️⃣ Generate hardware‑configuration.nix ----------
generate_hardware_config() {
  local hw_file="./hardware-configuration.nix"
  if [[ -f "${hw_file}" ]]; then
    info "hardware-configuration.nix already exists – skipping generation."
  else
    info "Generating hardware-configuration.nix (first‑time only)."
    # This command must be executed inside the WSL distro that will host the NixOS system.
    nixos-generate-config --root "$(pwd)" --dir "$(pwd)"
  fi
}

# ---------- 7️⃣ Rebuild the WSL system ----------
rebuild_wsl() {
  info "Building the NixOS‑WSL system (this may take a few minutes)…"
  # The flake defines a `nixosConfigurations.wsl` attribute.
  # Use sudo because we need to write to the system configuration inside the VM.
  sudo nixos-rebuild switch --flake ".#wsl"
}

# ---------- Main execution flow ----------
main() {
  info "===== Starting NixOS‑WSL bootstrap ====="

  ensure_nix_conf
  install_nix_direnv
  install_home_manager
  migrate_legacy_home_nix
  create_home_nix_if_missing
  generate_hardware_config
  rebuild_wsl

  info "===== Bootstrap complete! ====="
  echo
  echo "⚠️  IMPORTANT: Restart the WSL VM so the new system takes effect:"
  echo "    wsl --shutdown"
  echo "    wsl"
  echo
  echo "You can now use the dev‑shells, e.g.:"
  echo "    cd ~/repos/my‑first‑proj"
  echo "    direnv allow   # loads the profile you defined in .envrc"
  echo "    nix develop .#typescript   # manual invocation if you prefer"
  echo
}

main "$@"